USE [master]
GO

CREATE DATABASE [BoroMainDB]
GO

USE [BoroMainDB]
GO

CREATE TABLE Users (
    UserId UNIQUEIDENTIFIER PRIMARY KEY,
    FacebookId NVARCHAR(50) NOT NULL,
    Email NVARCHAR(256) NOT NULL,
    FirstName NVARCHAR(50) NOT NULL,
    LastName NVARCHAR(50) NOT NULL,
    About NVARCHAR(MAX) NOT NULL,
    DateJoined DATETIME NOT NULL,
    Latitude FLOAT NOT NULL,
    Longitude FLOAT NOT NULL
);

GO

CREATE TABLE Items (
    ItemId UNIQUEIDENTIFIER NOT NULL,
    Title NVARCHAR(255) NOT NULL DEFAULT '',
    Description NVARCHAR(MAX),
    OwnerId UNIQUEIDENTIFIER NOT NULL,
    Condition NVARCHAR(50) NOT NULL DEFAULT '',
    Categories NVARCHAR(255) NOT NULL DEFAULT '',
    Latitude FLOAT NOT NULL DEFAULT 0,
    Longitude FLOAT NOT NULL DEFAULT 0,
    CONSTRAINT PK_Items PRIMARY KEY CLUSTERED (ItemId)
);

GO

CREATE TABLE ItemImages (
    ImageId UNIQUEIDENTIFIER NOT NULL,
    ItemId UNIQUEIDENTIFIER NOT NULL,
    ImageMetaData NVARCHAR(MAX) NOT NULL DEFAULT '',
    ImageData VARBINARY(MAX) NOT NULL DEFAULT 0x,
    CONSTRAINT PK_ItemImages PRIMARY KEY CLUSTERED (ImageId),
    CONSTRAINT FK_ItemImages_Items FOREIGN KEY (ItemId) REFERENCES Items(ItemId)
);

GO

CREATE TABLE Reservations (
    ReservationId UNIQUEIDENTIFIER NOT NULL,
    ItemId UNIQUEIDENTIFIER NOT NULL,
    BorrowerId UNIQUEIDENTIFIER NOT NULL,
    LenderId UNIQUEIDENTIFIER NOT NULL,
    StartDate DATETIME NOT NULL,
    EndDate DATETIME NOT NULL,
    Status INT NOT NULL,
    CONSTRAINT PK_Reservations PRIMARY KEY CLUSTERED (ReservationId),
    CONSTRAINT FK_Reservations_Items FOREIGN KEY (ItemId) REFERENCES Items(ItemId),
    CONSTRAINT FK_Reservations_Borrowers FOREIGN KEY (BorrowerId) REFERENCES Users(UserId),
    CONSTRAINT FK_Reservations_Lenders FOREIGN KEY (LenderId) REFERENCES Users(UserId)
);

GO

